### ISSUE TITLE
SVRG  does not work

### ISSUE THREAD

**Issue by Hulalazz** [kilianFatras/variance_reduced_neural_networks#1]
I fork the code of SVRG to a neural network for MNIST and output figures are the same as yours for CIFAR10

**Comment by kilianFatras** [comment]
Hello,

Sorry for the delay, I just saw your issue now. I just tried my code over the MNIST dataset and I got really different results from CIFAR10 (and much better because MNIST is simpler, see attached). So I think my code works. Furthermore, I tried my code over a convex problem (optimization_algorithms_convex_case.ipynb) and all my codes have the correct theoretical behaviour.
![mnist_svrg](https://user-images.githubusercontent.com/22875363/40294415-51eb6794-5c8a-11e8-8d2a-ad1cc425e8f0.png)
